Received: PacketLobbyInfoData_V1(
    header=PacketHeader(
            packetFormat=2020, 
            gameMajorVersion=1, 
            gameMinorVersion=16, 
            packetVersion=1, 
            packetId=9, 
            sessionUID=0, 
            sessionTime=0.0, 
            frameIdentifier=0, 
            playerCarIndex=0, 
            secondaryPlayerCarIndex=0), 
        numPlayers=3, 
        lobbyPlayers=[
            LobbyInfoData_V1(aiControlled=0, teamId=0, nationality=0, name=b'Player', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=0, nationality=78, name=b'Player', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=58, name=b'Player', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
            LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0),
             LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0),
              LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0),
               LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0), 
               LobbyInfoData_V1(aiControlled=0, teamId=255, nationality=0, name=b'', readyStatus=0)])