PacketSessionData_V1(
    header=PacketHeader(
        packetFormat=2020, 
        gameMajorVersion=1,
        gameMinorVersion=16, 
        packetVersion=1, 
        packetId=1, 
        sessionUID=60379970896317530, 
        sessionTime=87.89685821533203, 
        frameIdentifier=1829, 
        playerCarIndex=0, 
        secondaryPlayerCarIndex=255), 
        
    weather=0, 
    trackTemperature=36, 
    airTemperature=29, 
    totalLaps=1, 
    trackLength=3826, 
    sessionType=12, 
    trackId=21, 
    formula=0, 
    sessionTimeLeft=0, 
    sessionDuration=600, 
    pitSpeedLimit=80, 
    gamePaused=0, 
    isSpectating=0, 
    spectatorCarIndex=255, 
    sliProNativeSupport=0, 
    numMarshalZones=8, 

    marshalZones=[
        MarshalZone_V1(zoneStart=0.9354672431945801, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.15203413367271423, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.24413104355335236, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.31199076771736145, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.47098082304000854, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.5667693614959717, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.7206792235374451, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.8453541994094849, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0), 
        MarshalZone_V1(zoneStart=0.0, zoneFlag=0)], 

    safetyCarStatus=0, 
    networkGame=0, 
    numWeatherForecastSamples=0, 

    weatherForecastSamples=[
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0),
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0), 
        WeatherForecastSample(sessionType=0, timeOffset=0, weather=0, trackTemperature=0, airTemperature=0)])